//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "reports")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub report_id: i32,
    pub month: Date,
    pub total_orders: i32,
    #[sea_orm(column_type = "Decimal(Some((12, 2)))")]
    pub total_income: Decimal,
    #[sea_orm(column_type = "Decimal(Some((12, 2)))")]
    pub total_expenses: Decimal,
    #[sea_orm(column_type = "Decimal(Some((12, 2)))")]
    pub net_profit: Decimal,
    pub generated_at: DateTime,
    #[sea_orm(column_type = "JsonBinary")]
    pub daily_data: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
